# Generated by Django 4.2.7 on 2023-12-01 10:24

import apps.recipes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name of recipe')),
                ('description', models.CharField(max_length=250, verbose_name='Description of recipe')),
                ('prep_time', models.PositiveSmallIntegerField(verbose_name='Preparation time')),
                ('cook_time', models.PositiveSmallIntegerField(verbose_name='Cook time')),
                ('notes', models.CharField(max_length=250, verbose_name="Author's notes")),
                ('servings', models.PositiveSmallIntegerField(verbose_name='Servings')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=6, verbose_name='Difficulty')),
                ('picture', models.ImageField(upload_to=None, verbose_name='Picture of prepared food')),
                ('alt_text', models.CharField(max_length=180, verbose_name='Alt text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
