# Generated by Django 4.2.7 on 2023-12-02 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_add_recipe_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='picture',
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(verbose_name='Instruction step number')),
                ('description', models.CharField(max_length=250, verbose_name='Instruction description')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Ingredient order number')),
                ('name', models.CharField(max_length=50, verbose_name='Ingredient name')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Ingredient quantity')),
                ('measurement', models.CharField(blank=True, max_length=50, verbose_name='Ingredient measurement')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
    ]
