# Generated by Django 4.2.7 on 2023-12-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_tag_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('DIETARY_PREFERENCE', 'dietary preference'), ('COURSE', 'course'), ('DIFFICULTY', 'difficulty'), ('CUSTOM', 'custom')], default='CUSTOM', max_length=20, verbose_name='Tag type'),
        ),
    ]
