# Generated by Django 4.2.7 on 2023-12-05 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_add_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Recipe is private'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description of recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(max_length=500, verbose_name="Author's notes"),
        ),
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name of cookbook')),
                ('description', models.TextField(max_length=500, verbose_name='Description of cookbook')),
                ('is_private', models.BooleanField(default=False, verbose_name='Cookbook is private')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbooks', to=settings.AUTH_USER_MODEL)),
                ('recipes', models.ManyToManyField(blank=True, related_name='included_in_cookbooks', to='recipes.recipe')),
                ('tags', models.ManyToManyField(related_name='associated_cookbooks', to='recipes.tag')),
            ],
        ),
    ]
