# Generated by Django 4.2.7 on 2023-12-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_recipe_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
