# Generated by Django 4.2.7 on 2023-12-05 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecipePictureUpload',
            fields=[
                ('pictureupload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uploads.pictureupload')),
            ],
            bases=('uploads.pictureupload',),
        ),
        migrations.CreateModel(
            name='UserProfilePictureUpload',
            fields=[
                ('pictureupload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uploads.pictureupload')),
            ],
            bases=('uploads.pictureupload',),
        ),
    ]
